### ISSUE TITLE
add golint (and others)

### ISSUE THREAD

**Issue by erzz** [erzz/workflows#57]
Below (taken from rpim-service-products) plus some reports? 

Any other go related jobs?

The whole shebang of https://golangci-lint.run/usage/linters/ or pick n mix

```yaml
lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...
```
